import type { TSchema } from "@sinclair/typebox";
import {
  AgentEventSchema,
  AgentIdentityParamsSchema,
  AgentIdentityResultSchema,
  AgentParamsSchema,
  AgentWaitParamsSchema,
  PollParamsSchema,
  SendParamsSchema,
  WakeParamsSchema,
} from "./agent.js";
import {
  AgentSummarySchema,
  AgentsCreateParamsSchema,
  AgentsCreateResultSchema,
  AgentsDeleteParamsSchema,
  AgentsDeleteResultSchema,
  AgentsFileEntrySchema,
  AgentsFilesGetParamsSchema,
  AgentsFilesGetResultSchema,
  AgentsFilesListParamsSchema,
  AgentsFilesListResultSchema,
  AgentsFilesSetParamsSchema,
  AgentsFilesSetResultSchema,
  AgentsListParamsSchema,
  AgentsListResultSchema,
  AgentsUpdateParamsSchema,
  AgentsUpdateResultSchema,
  ModelChoiceSchema,
  ModelsListParamsSchema,
  ModelsListResultSchema,
  SkillsBinsParamsSchema,
  SkillsBinsResultSchema,
  SkillsInstallParamsSchema,
  SkillsStatusParamsSchema,
  SkillsUpdateParamsSchema,
} from "./agents-models-skills.js";
import {
  BusAckParamsSchema,
  BusAckResultSchema,
  BusDeliverySchema,
  BusMessageEventSchema,
  BusMessageSchema,
  BusPublishParamsSchema,
  BusPublishResultSchema,
  BusPullParamsSchema,
  BusPullResultSchema,
} from "./bus.js";
import {
  ChannelsLogoutParamsSchema,
  ChannelsStatusParamsSchema,
  ChannelsStatusResultSchema,
} from "./channels.js";
import {
  ConfigApplyParamsSchema,
  ConfigGetParamsSchema,
  ConfigPatchParamsSchema,
  ConfigSchemaParamsSchema,
  ConfigSchemaResponseSchema,
  ConfigSetParamsSchema,
  UpdateRunParamsSchema,
} from "./config.js";
import {
  CronAddParamsSchema,
  CronJobSchema,
  CronListParamsSchema,
  CronRemoveParamsSchema,
  CronRunLogEntrySchema,
  CronRunParamsSchema,
  CronRunsParamsSchema,
  CronStatusParamsSchema,
  CronUpdateParamsSchema,
} from "./cron.js";
import {
  DevicePairApproveParamsSchema,
  DevicePairListParamsSchema,
  DevicePairRejectParamsSchema,
  DevicePairRequestedEventSchema,
  DevicePairResolvedEventSchema,
  DeviceTokenRevokeParamsSchema,
  DeviceTokenRotateParamsSchema,
} from "./devices.js";
import {
  ExecApprovalsGetParamsSchema,
  ExecApprovalsNodeGetParamsSchema,
  ExecApprovalsNodeSetParamsSchema,
  ExecApprovalsSetParamsSchema,
  ExecApprovalsSnapshotSchema,
  ExecApprovalRequestParamsSchema,
  ExecApprovalResolveParamsSchema,
} from "./exec-approvals.js";
import {
  ConnectParamsSchema,
  ErrorShapeSchema,
  EventFrameSchema,
  GatewayFrameSchema,
  HelloOkSchema,
  RequestFrameSchema,
  ResponseFrameSchema,
  ShutdownEventSchema,
  TickEventSchema,
} from "./frames.js";
import {
  ChatAbortParamsSchema,
  ChatEventSchema,
  ChatHistoryParamsSchema,
  ChatInjectParamsSchema,
  ChatSendParamsSchema,
  LogsTailParamsSchema,
  LogsTailResultSchema,
} from "./logs-chat.js";
import {
  NodeDescribeParamsSchema,
  NodeEventParamsSchema,
  NodeInvokeParamsSchema,
  NodeInvokeResultParamsSchema,
  NodeInvokeRequestEventSchema,
  NodeListParamsSchema,
  NodePairApproveParamsSchema,
  NodePairListParamsSchema,
  NodePairRejectParamsSchema,
  NodePairRequestParamsSchema,
  NodePairVerifyParamsSchema,
  NodeRenameParamsSchema,
} from "./nodes.js";
import {
  ProjectSchema,
  ProjectsArchiveParamsSchema,
  ProjectsChangedEventSchema,
  ProjectsCreateParamsSchema,
  ProjectsGetParamsSchema,
  ProjectsListParamsSchema,
  ProjectsListResultSchema,
  ProjectsUpdateParamsSchema,
} from "./projects.js";
import {
  SessionsCompactParamsSchema,
  SessionsDeleteParamsSchema,
  SessionsListParamsSchema,
  SessionsPatchParamsSchema,
  SessionsPreviewParamsSchema,
  SessionsResetParamsSchema,
  SessionsResolveParamsSchema,
  SessionsUsageParamsSchema,
} from "./sessions.js";
import { PresenceEntrySchema, SnapshotSchema, StateVersionSchema } from "./snapshot.js";
import {
  TaskSchema,
  TaskAttemptSchema,
  TaskClaimSchema,
  TaskWorkerStatusSchema,
  TasksAttemptChangedEventSchema,
  TasksAttemptFailParamsSchema,
  TasksAttemptFailResultSchema,
  TasksAttemptFinishParamsSchema,
  TasksAttemptFinishResultSchema,
  TasksAttemptStartParamsSchema,
  TasksAttemptStartResultSchema,
  TasksClaimedEventSchema,
  TasksClaimNextParamsSchema,
  TasksClaimNextResultSchema,
  TasksChangedEventSchema,
  TasksCreateParamsSchema,
  TasksGetParamsSchema,
  TasksLeaseHeartbeatParamsSchema,
  TasksLeaseHeartbeatResultSchema,
  TasksListParamsSchema,
  TasksListResultSchema,
  TasksRequeueParamsSchema,
  TasksRequeueResultSchema,
  TasksWorkerChangedEventSchema,
  TasksTransitionParamsSchema,
  TasksUpdateParamsSchema,
} from "./tasks.js";
import {
  TeamMemberSchema,
  TeamSchema,
  TeamWithMembersResultSchema,
  TeamsChangedEventSchema,
  TeamsCreateParamsSchema,
  TeamsDeleteParamsSchema,
  TeamsGetByNameParamsSchema,
  TeamsGetParamsSchema,
  TeamsListParamsSchema,
  TeamsListResultSchema,
  TeamsMembersAddParamsSchema,
  TeamsMembersRemoveParamsSchema,
  TeamsUpdateParamsSchema,
} from "./teams.js";
import {
  WizardCancelParamsSchema,
  WizardNextParamsSchema,
  WizardNextResultSchema,
  WizardStartParamsSchema,
  WizardStartResultSchema,
  WizardStatusParamsSchema,
  WizardStatusResultSchema,
  WizardStepSchema,
} from "./wizard.js";

export const ProtocolSchemas: Record<string, TSchema> = {
  ConnectParams: ConnectParamsSchema,
  HelloOk: HelloOkSchema,
  RequestFrame: RequestFrameSchema,
  ResponseFrame: ResponseFrameSchema,
  EventFrame: EventFrameSchema,
  GatewayFrame: GatewayFrameSchema,
  PresenceEntry: PresenceEntrySchema,
  StateVersion: StateVersionSchema,
  Snapshot: SnapshotSchema,
  ErrorShape: ErrorShapeSchema,
  AgentEvent: AgentEventSchema,
  SendParams: SendParamsSchema,
  PollParams: PollParamsSchema,
  AgentParams: AgentParamsSchema,
  AgentIdentityParams: AgentIdentityParamsSchema,
  AgentIdentityResult: AgentIdentityResultSchema,
  AgentWaitParams: AgentWaitParamsSchema,
  WakeParams: WakeParamsSchema,
  NodePairRequestParams: NodePairRequestParamsSchema,
  NodePairListParams: NodePairListParamsSchema,
  NodePairApproveParams: NodePairApproveParamsSchema,
  NodePairRejectParams: NodePairRejectParamsSchema,
  NodePairVerifyParams: NodePairVerifyParamsSchema,
  NodeRenameParams: NodeRenameParamsSchema,
  NodeListParams: NodeListParamsSchema,
  NodeDescribeParams: NodeDescribeParamsSchema,
  NodeInvokeParams: NodeInvokeParamsSchema,
  NodeInvokeResultParams: NodeInvokeResultParamsSchema,
  NodeEventParams: NodeEventParamsSchema,
  NodeInvokeRequestEvent: NodeInvokeRequestEventSchema,
  Project: ProjectSchema,
  ProjectsListParams: ProjectsListParamsSchema,
  ProjectsListResult: ProjectsListResultSchema,
  ProjectsCreateParams: ProjectsCreateParamsSchema,
  ProjectsGetParams: ProjectsGetParamsSchema,
  ProjectsUpdateParams: ProjectsUpdateParamsSchema,
  ProjectsArchiveParams: ProjectsArchiveParamsSchema,
  ProjectsChangedEvent: ProjectsChangedEventSchema,
  SessionsListParams: SessionsListParamsSchema,
  SessionsPreviewParams: SessionsPreviewParamsSchema,
  SessionsResolveParams: SessionsResolveParamsSchema,
  SessionsPatchParams: SessionsPatchParamsSchema,
  SessionsResetParams: SessionsResetParamsSchema,
  SessionsDeleteParams: SessionsDeleteParamsSchema,
  SessionsCompactParams: SessionsCompactParamsSchema,
  SessionsUsageParams: SessionsUsageParamsSchema,
  ConfigGetParams: ConfigGetParamsSchema,
  ConfigSetParams: ConfigSetParamsSchema,
  ConfigApplyParams: ConfigApplyParamsSchema,
  ConfigPatchParams: ConfigPatchParamsSchema,
  ConfigSchemaParams: ConfigSchemaParamsSchema,
  ConfigSchemaResponse: ConfigSchemaResponseSchema,
  WizardStartParams: WizardStartParamsSchema,
  WizardNextParams: WizardNextParamsSchema,
  WizardCancelParams: WizardCancelParamsSchema,
  WizardStatusParams: WizardStatusParamsSchema,
  WizardStep: WizardStepSchema,
  WizardNextResult: WizardNextResultSchema,
  WizardStartResult: WizardStartResultSchema,
  WizardStatusResult: WizardStatusResultSchema,
  ChannelsStatusParams: ChannelsStatusParamsSchema,
  ChannelsStatusResult: ChannelsStatusResultSchema,
  ChannelsLogoutParams: ChannelsLogoutParamsSchema,
  AgentSummary: AgentSummarySchema,
  AgentsCreateParams: AgentsCreateParamsSchema,
  AgentsCreateResult: AgentsCreateResultSchema,
  AgentsUpdateParams: AgentsUpdateParamsSchema,
  AgentsUpdateResult: AgentsUpdateResultSchema,
  AgentsDeleteParams: AgentsDeleteParamsSchema,
  AgentsDeleteResult: AgentsDeleteResultSchema,
  AgentsFileEntry: AgentsFileEntrySchema,
  AgentsFilesListParams: AgentsFilesListParamsSchema,
  AgentsFilesListResult: AgentsFilesListResultSchema,
  AgentsFilesGetParams: AgentsFilesGetParamsSchema,
  AgentsFilesGetResult: AgentsFilesGetResultSchema,
  AgentsFilesSetParams: AgentsFilesSetParamsSchema,
  AgentsFilesSetResult: AgentsFilesSetResultSchema,
  AgentsListParams: AgentsListParamsSchema,
  AgentsListResult: AgentsListResultSchema,
  ModelChoice: ModelChoiceSchema,
  ModelsListParams: ModelsListParamsSchema,
  ModelsListResult: ModelsListResultSchema,
  SkillsStatusParams: SkillsStatusParamsSchema,
  SkillsBinsParams: SkillsBinsParamsSchema,
  SkillsBinsResult: SkillsBinsResultSchema,
  SkillsInstallParams: SkillsInstallParamsSchema,
  SkillsUpdateParams: SkillsUpdateParamsSchema,
  CronJob: CronJobSchema,
  CronListParams: CronListParamsSchema,
  CronStatusParams: CronStatusParamsSchema,
  CronAddParams: CronAddParamsSchema,
  CronUpdateParams: CronUpdateParamsSchema,
  CronRemoveParams: CronRemoveParamsSchema,
  CronRunParams: CronRunParamsSchema,
  CronRunsParams: CronRunsParamsSchema,
  CronRunLogEntry: CronRunLogEntrySchema,
  LogsTailParams: LogsTailParamsSchema,
  LogsTailResult: LogsTailResultSchema,
  ExecApprovalsGetParams: ExecApprovalsGetParamsSchema,
  ExecApprovalsSetParams: ExecApprovalsSetParamsSchema,
  ExecApprovalsNodeGetParams: ExecApprovalsNodeGetParamsSchema,
  ExecApprovalsNodeSetParams: ExecApprovalsNodeSetParamsSchema,
  ExecApprovalsSnapshot: ExecApprovalsSnapshotSchema,
  ExecApprovalRequestParams: ExecApprovalRequestParamsSchema,
  ExecApprovalResolveParams: ExecApprovalResolveParamsSchema,
  DevicePairListParams: DevicePairListParamsSchema,
  DevicePairApproveParams: DevicePairApproveParamsSchema,
  DevicePairRejectParams: DevicePairRejectParamsSchema,
  DeviceTokenRotateParams: DeviceTokenRotateParamsSchema,
  DeviceTokenRevokeParams: DeviceTokenRevokeParamsSchema,
  DevicePairRequestedEvent: DevicePairRequestedEventSchema,
  DevicePairResolvedEvent: DevicePairResolvedEventSchema,
  BusMessage: BusMessageSchema,
  BusDelivery: BusDeliverySchema,
  BusPublishParams: BusPublishParamsSchema,
  BusPublishResult: BusPublishResultSchema,
  BusPullParams: BusPullParamsSchema,
  BusPullResult: BusPullResultSchema,
  BusAckParams: BusAckParamsSchema,
  BusAckResult: BusAckResultSchema,
  BusMessageEvent: BusMessageEventSchema,
  Team: TeamSchema,
  TeamMember: TeamMemberSchema,
  TeamWithMembersResult: TeamWithMembersResultSchema,
  TeamsListParams: TeamsListParamsSchema,
  TeamsListResult: TeamsListResultSchema,
  TeamsCreateParams: TeamsCreateParamsSchema,
  TeamsGetParams: TeamsGetParamsSchema,
  TeamsGetByNameParams: TeamsGetByNameParamsSchema,
  TeamsUpdateParams: TeamsUpdateParamsSchema,
  TeamsDeleteParams: TeamsDeleteParamsSchema,
  TeamsMembersAddParams: TeamsMembersAddParamsSchema,
  TeamsMembersRemoveParams: TeamsMembersRemoveParamsSchema,
  TeamsChangedEvent: TeamsChangedEventSchema,
  Task: TaskSchema,
  TaskClaim: TaskClaimSchema,
  TaskAttempt: TaskAttemptSchema,
  TasksListParams: TasksListParamsSchema,
  TasksListResult: TasksListResultSchema,
  TasksCreateParams: TasksCreateParamsSchema,
  TasksGetParams: TasksGetParamsSchema,
  TasksUpdateParams: TasksUpdateParamsSchema,
  TasksTransitionParams: TasksTransitionParamsSchema,
  TasksClaimNextParams: TasksClaimNextParamsSchema,
  TasksClaimNextResult: TasksClaimNextResultSchema,
  TasksLeaseHeartbeatParams: TasksLeaseHeartbeatParamsSchema,
  TasksLeaseHeartbeatResult: TasksLeaseHeartbeatResultSchema,
  TasksAttemptStartParams: TasksAttemptStartParamsSchema,
  TasksAttemptStartResult: TasksAttemptStartResultSchema,
  TasksAttemptFinishParams: TasksAttemptFinishParamsSchema,
  TasksAttemptFinishResult: TasksAttemptFinishResultSchema,
  TasksAttemptFailParams: TasksAttemptFailParamsSchema,
  TasksAttemptFailResult: TasksAttemptFailResultSchema,
  TasksRequeueParams: TasksRequeueParamsSchema,
  TasksRequeueResult: TasksRequeueResultSchema,
  TasksChangedEvent: TasksChangedEventSchema,
  TasksClaimedEvent: TasksClaimedEventSchema,
  TasksAttemptChangedEvent: TasksAttemptChangedEventSchema,
  TaskWorkerStatus: TaskWorkerStatusSchema,
  TasksWorkerChangedEvent: TasksWorkerChangedEventSchema,
  ChatHistoryParams: ChatHistoryParamsSchema,
  ChatSendParams: ChatSendParamsSchema,
  ChatAbortParams: ChatAbortParamsSchema,
  ChatInjectParams: ChatInjectParamsSchema,
  ChatEvent: ChatEventSchema,
  UpdateRunParams: UpdateRunParamsSchema,
  TickEvent: TickEventSchema,
  ShutdownEvent: ShutdownEventSchema,
};

export const PROTOCOL_VERSION = 3 as const;
